version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # this is the bit that mounts the config file
  node-app:
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    build:
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - JWT_EXPIRES=${JWT_EXPIRES}
    command: npm start
