version: '3'
services:
  nginx:
    image: nginx:stable-alpine  # Corrected image name here
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-app:
    build: .
